import assert from "node:assert/strict"
import { mkdtemp, mkdir, readFile, readdir, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import path from "node:path"
import test from "node:test"
import {
  ValidationFailure,
  extractReferences,
  preparePublication,
  stripCode,
} from "./prepare-publication.ts"

type Files = Record<string, string>

async function withVault(files: Files): Promise<{
  run: (overrides?: Record<string, unknown>) => Promise<Awaited<ReturnType<typeof preparePublication>>>
  vaultDir: string
  write: (files: Files) => Promise<void>
}> {
  const root = await mkdtemp(path.join(tmpdir(), "publication-prep-"))
  const vaultDir = path.join(root, "vault")

  const write = async (contents: Files): Promise<void> => {
    for (const [relative, body] of Object.entries(contents)) {
      const target = path.join(vaultDir, relative)
      await mkdir(path.dirname(target), { recursive: true })
      await writeFile(target, body, "utf8")
    }
  }

  await write(files)
  return {
    vaultDir,
    write,
    run: (overrides = {}) =>
      preparePublication({
        vaultDir,
        quartoDir: path.join(root, "generated/site"),
        ...overrides,
      }),
  }
}

function note(title: string, extra: string, body: string): string {
  return `---\ntitle: ${title}\n${extra}---\n\n${body}\n`
}

async function messagesFrom(run: () => Promise<unknown>): Promise<string[]> {
  try {
    await run()
  } catch (error) {
    assert.ok(error instanceof ValidationFailure)
    return error.problems.map((problem) => problem.message)
  }
  assert.fail("expected publication prep to fail")
}

test("puts every published document in the render allowlist and skips the rest", async () => {
  const vault = await withVault({
    "notes/public.md": note("Public", "publish: true\n", "Links to [Research Note](../research/study.qmd)."),
    "notes/private.md": note("Private", "publish: false\n", "Secret."),
    "notes/implicit.md": note("Implicit", "", "No publish key at all."),
    "research/study.qmd": note(
      "Research Note",
      "publish: true\n",
      "Prose stays.\n\n```{python}\nsecret = 1\n```",
    ),
  })

  const result = await vault.run()

  assert.deepEqual(
    result.published.map((document) => document.slug).sort(),
    ["notes/public", "research/study"],
  )
  // Both source types are listed. Quarto renders the whole vault now, so an
  // allowlist of .qmd alone would drop every prose page from the site.
  assert.equal(
    await readFile(path.join(vault.vaultDir, "_quarto-publish.yml"), "utf8"),
    '# Generated by scripts/prepare-publication.ts; do not edit.\nproject:\n  render:\n    - "notes/public.md"\n    - "research/study.qmd"\n',
  )
})

test("ignores nested *_hidden trees regardless of frontmatter", async () => {
  const vault = await withVault({
    "courses/public.qmd": note("Public", "publish: true\n", "Visible."),
    "courses/_hidden/experiment.qmd": note(
      "Private experiment",
      "publish: true\n",
      "Must remain local despite the accidental flag.",
    ),
    "courses/_hidden/assets/secret.csv": "secret",
    // No leading underscore, so the "_"-prefix rule alone would walk into it.
    "courses/drafts_hidden/notes.md": note("Draft notes", "publish: true\n", "Also local."),
    "courses/drafts_hidden/assets/secret.csv": "secret",
    // The marker is the `_hidden` suffix, not the word anywhere in the name.
    // (Underscores are not slug-safe, so a public folder cannot end in one
    // by accident -- the suffix only ever appears on deliberate private trees.)
    "courses/hidden-costs/notes.md": note("Hidden costs", "publish: true\n", "An ordinary note."),
  })

  const result = await vault.run()

  assert.deepEqual(
    result.documents.map((document) => document.sourcePath).sort(),
    ["courses/hidden-costs/notes.md", "courses/public.qmd"],
  )
  assert.doesNotMatch(
    await readFile(path.join(vault.vaultDir, "_quarto-publish.yml"), "utf8"),
    /_hidden/,
  )
})

test("ignores hidden notes regardless of frontmatter, and fails links into them", async () => {
  const vault = await withVault({
    "courses/public.md": note("Public", "publish: true\n", "Visible."),
    "courses/draft.hidden.md": note(
      "Hidden draft",
      "publish: true\n",
      "Must remain local despite the accidental flag.",
    ),
    "courses/experiment.hidden.qmd": note(
      "Hidden experiment",
      "publish: true\n",
      "Must never reach the Quarto render allowlist.",
    ),
    // The marker is the `.hidden.` suffix, not the word anywhere in the name.
    "courses/hidden-costs.md": note("Hidden costs", "publish: true\n", "An ordinary note."),
  })

  const result = await vault.run()
  assert.deepEqual(
    result.documents.map((document) => document.sourcePath).sort(),
    ["courses/hidden-costs.md", "courses/public.md"],
  )
  assert.doesNotMatch(
    await readFile(path.join(vault.vaultDir, "_quarto-publish.yml"), "utf8"),
    /\.hidden\./,
  )

  await vault.write({
    "courses/public.md": note("Public", "publish: true\n", "See [draft](draft.hidden.md)."),
  })
  const messages = await messagesFrom(() => vault.run())
  assert.ok(messages.some((message) => message.includes("draft.hidden.md")))
})

test("reports only attachments that published content references", async () => {
  const vault = await withVault({
    "index.md": note(
      "Index",
      "publish: true\n",
      "![diagram](attachments/diagram.svg) and [pdf](attachments/paper.pdf)",
    ),
    "draft.md": note("Draft", "publish: false\n", "![unused](attachments/unused.svg)"),
    "attachments/diagram.svg": "<svg/>",
    "attachments/paper.pdf": "%PDF",
    "attachments/unused.svg": "<svg/>",
  })

  const result = await vault.run()

  assert.deepEqual(result.attachments, ["attachments/diagram.svg", "attachments/paper.pdf"])
})

test("regenerates the allowlist instead of patching it", async () => {
  const vault = await withVault({ "keep.md": note("Keep", "publish: true\n", "Body.") })
  await vault.run()

  await vault.write({ "keep.md": note("Keep", "publish: false\n", "Body.") })
  await vault.run()

  // An empty render field can fall back to project discovery, which would
  // render the whole vault. The zero-document case has to say "nothing".
  assert.equal(
    await readFile(path.join(vault.vaultDir, "_quarto-publish.yml"), "utf8"),
    '# Generated by scripts/prepare-publication.ts; do not edit.\nproject:\n  render:\n    - "!**/*"\n',
  )
})

test("fails when published content links to an unpublished note", async () => {
  const vault = await withVault({
    "index.md": note("Index", "publish: true\n", "See [Hidden](hidden.md)."),
    "hidden.md": note("Hidden", "publish: false\n", "Not public."),
  })

  const messages = await messagesFrom(vault.run)

  assert.deepEqual(messages, [
    `[Hidden](hidden.md) points at unpublished ${vault.vaultDir}/hidden.md`,
  ])
})

test("fails on links and embeds that resolve to nothing", async () => {
  const vault = await withVault({
    "index.md": note(
      "Index",
      "publish: true\n",
      "[Nowhere](nowhere.md) and ![gone](missing.png)",
    ),
  })

  const messages = await messagesFrom(vault.run)

  assert.equal(messages.length, 2)
  assert.match(messages[0], /no published note or attachment matches/)
  assert.match(messages[1], /no such attachment/)
})

test("fails on unusable frontmatter", async () => {
  const vault = await withVault({
    "no-frontmatter.md": "# Body only\n",
    "no-title.md": "---\npublish: true\n---\n\nBody\n",
    "bad-publish.md": note("Bad Publish", "publish: yes please\n", "Body"),
    "bad-aliases.md": note("Bad Aliases", "aliases: { a: b }\n", "Body"),
  })

  const messages = await messagesFrom(vault.run)

  assert.deepEqual(messages.sort(), [
    "`aliases` must be a list of strings",
    "`publish` must be true or false",
    "frontmatter needs a non-empty `title`",
    "missing or unparsable YAML frontmatter",
  ])
})

test("fails when a published path cannot become a predictable slug", async () => {
  const vault = await withVault({
    "notes/Monte Carlo.md": note("Monte Carlo", "publish: true\n", "Body"),
  })

  const messages = await messagesFrom(vault.run)

  assert.match(messages[0], /not slug-safe/)
})

// Two pages cannot both redirect from one URL. Titles and aliases no longer
// collide with each other -- an alias is site-absolute, a title is prose -- so
// this is the collision that is left.
test("fails when two published notes claim the same alias", async () => {
  const vault = await withVault({
    "a.md": note("First", "publish: true\naliases:\n  - /old-url\n", "Body"),
    "b.md": note("Second", "publish: true\naliases:\n  - /old-url\n", "Body"),
  })

  const messages = await messagesFrom(vault.run)

  assert.deepEqual(messages, [`alias "/old-url" is already claimed by ${vault.vaultDir}/a.md`])
})

test("fails when a .md and a .qmd would occupy the same URL", async () => {
  const vault = await withVault({
    "research/study.md": note("Study Notes", "publish: true\n", "Body"),
    "research/study.qmd": note("Study", "publish: true\n", "Body"),
  })

  const messages = await messagesFrom(vault.run)

  assert.deepEqual(messages, [
    `slug "research/study" collides with ${vault.vaultDir}/research/study.md`,
  ])
})

test("rejects Quarto artifacts that no published document explains", async () => {
  const vault = await withVault({ "research/study.qmd": note("Study", "publish: true\n", "Body") })
  const options = { quartoDir: path.join(vault.vaultDir, "../generated/site") }
  await mkdir(path.join(options.quartoDir, "research"), { recursive: true })
  await writeFile(path.join(options.quartoDir, "research/study.html"), "<html/>", "utf8")
  await writeFile(path.join(options.quartoDir, "research/private.html"), "<html/>", "utf8")

  const messages = await messagesFrom(() => vault.run(options))

  assert.deepEqual(messages, [
    "rendered artifact has no matching published document; delete it and re-render",
  ])
})

test("requires a rendered artifact for every published .qmd under --require-quarto", async () => {
  const vault = await withVault({ "research/study.qmd": note("Study", "publish: true\n", "Body") })

  const messages = await messagesFrom(() => vault.run({ requireQuarto: true }))

  assert.match(messages[0], /run `quarto render`/)
})

test("rejects frozen output belonging to an unpublished document", async () => {
  const vault = await withVault({
    "research/study.qmd": note("Study", "publish: true\n", "Body"),
    "research/private.qmd": note("Private Study", "publish: false\n", "Body"),
  })
  await vault.write({
    "_freeze/research/study/execute-results/html.json": "{}",
    "_freeze/research/private/execute-results/html.json": "{}",
  })

  const messages = await messagesFrom(vault.run)

  assert.deepEqual(messages, ["frozen output for a document that is not published; delete it"])
})

test("ignores link syntax inside code", () => {
  const body =
    "Real [t](target.md).\n\n```text\n[n](not-a-link.md)\n```\n\nInline `[a](also-not.md)`.\n"

  assert.deepEqual(
    extractReferences(body).map((reference) => reference.target),
    ["target.md"],
  )
  assert.doesNotMatch(stripCode(body), /not-a-link/)
})

test("reads anchors and embeds out of Markdown link syntax", () => {
  const references = extractReferences("[shown](note.md#heading) ![alt](diagram.svg)")

  assert.deepEqual(references, [
    { raw: "[shown](note.md#heading)", target: "note.md", embed: false },
    { raw: "![alt](diagram.svg)", target: "diagram.svg", embed: true },
  ])
})

test("leaves external and anchor-only links alone", () => {
  const references = extractReferences("[x](https://example.com) [y](#section) [z](notes/a.md)")

  assert.deepEqual(
    references.map((reference) => reference.target),
    ["notes/a.md"],
  )
})

test("reads a bare index.md as this section's index, not the vault root", async () => {
  const vault = await withVault({
    // A root index.md must exist, or the ambiguity this pins down cannot arise.
    "index.md": note("Home", "publish: true\n", "Root."),
    "examples/index.md": note("Examples", "publish: true\n", "Section index."),
    "examples/one.md": note("One", "publish: true\n", "Back to [Examples](index.md)."),
  })

  const result = await vault.run()

  assert.equal(result.published.length, 3)
})

test("resolves a sibling link, and one that climbs a directory", async () => {
  const vault = await withVault({
    "index.md": note("Home", "publish: true\n", "Root."),
    "examples/one.md": note("One", "publish: true\n", "See [Two](two.md) and [Home](../index.md)."),
    "examples/two.md": note("Two", "publish: true\n", "Body."),
  })

  const result = await vault.run()

  assert.equal(result.published.length, 3)
})

test("rejects a target that only resolves from the vault root", async () => {
  const vault = await withVault({
    "index.md": note("Home", "publish: true\n", "Root."),
    // The old contract. It resolves against the document now, so this points
    // at examples/examples/two.md and does not exist.
    "examples/one.md": note("One", "publish: true\n", "See [Two](examples/two.md)."),
    "examples/two.md": note("Two", "publish: true\n", "Body."),
  })

  const messages = await messagesFrom(vault.run)

  assert.equal(messages.length, 1)
  assert.match(messages[0], /no published note or attachment matches/)
})

test("resolves an attachment link relative to the document", async () => {
  const vault = await withVault({
    "notes/figure.md": note("Figure", "publish: true\n", "![d](../attachments/diagram.svg)"),
    "attachments/diagram.svg": "<svg/>",
  })

  const result = await vault.run()

  assert.deepEqual(result.attachments, ["attachments/diagram.svg"])
})

test("rejects a leftover wikilink anywhere in the vault", async () => {
  const vault = await withVault({
    "notes/prose.md": note("Prose", "publish: true\n", "See [[Other Note]]."),
    "notes/other.md": note("Other Note", "publish: true\n", "Body."),
  })

  await assert.rejects(vault.run(), (error: unknown) => {
    assert.ok(error instanceof ValidationFailure)
    assert.match(String(error.message), /wikilink syntax is not supported/)
    return true
  })
})

test("rejects Obsidian syntax that Quarto would publish verbatim", async () => {
  const vault = await withVault({
    "notes/computed.qmd": note(
      "Computed",
      "publish: true\n",
      [
        "%%a note to self%%",
        "> [!note] Callout",
        "> Body.",
        "Some ==highlighted== text.",
      ].join("\n\n"),
    ),
  })

  const messages = await messagesFrom(() => vault.run())

  assert.equal(messages.length, 3)
  assert.match(messages.join("\n"), /comment syntax/)
  assert.match(messages.join("\n"), /callout/)
  assert.match(messages.join("\n"), /highlights/)
})

// Quarto callouts were rejected while a published .qmd was a body fragment with
// no Bootstrap behind it, which silently dropped the callout type. Quarto owns
// the chrome now, so Bootstrap is there and they are the supported form.
test("accepts Quarto callouts", async () => {
  const vault = await withVault({
    "notes/computed.qmd": note(
      "Computed",
      "publish: true\n",
      ['::: {.callout-note collapse="true"}', "## Title", "Body.", ":::"].join("\n\n"),
    ),
  })

  const result = await vault.run()

  assert.equal(result.published.length, 1)
})

test("rejects Obsidian-only syntax in Markdown too, not just Quarto", async () => {
  const vault = await withVault({
    "notes/prose.md": note(
      "Prose",
      "publish: true\n",
      "%%hidden%%\n\n> [!note] Callout\n> Body.\n\nSome ==highlighted== text.",
    ),
  })

  const messages = await messagesFrom(() => vault.run())

  // One renderer now, so .md has no dialect of its own to fall back on.
  assert.equal(messages.length, 3)
  assert.match(messages.join("\n"), /%%/)
  assert.match(messages.join("\n"), /callout/)
  assert.match(messages.join("\n"), /==text==/)
})

test("does not mistake code fences or comparisons for Obsidian syntax", async () => {
  const vault = await withVault({
    "notes/computed.qmd": note(
      "Computed",
      "publish: true\n",
      "Prose with a == b comparison.\n\n```python\n# %%cell%% and ==x== stay put\n```",
    ),
  })

  const result = await vault.run()

  assert.equal(result.published.length, 1)
})

test("--keep-quarto stages without discarding rendered artifacts", async () => {
  const vault = await withVault({
    "notes/computed.qmd": note("Computed", "publish: true\n", "Body."),
  })
  await vault.run({ requireQuarto: false, clearQuartoOutput: false })
  const quartoDir = path.join(vault.vaultDir, "..", "generated/site/notes")
  await mkdir(quartoDir, { recursive: true })
  await writeFile(path.join(quartoDir, "computed.html"), "<html></html>", "utf8")

  await vault.run({ clearQuartoOutput: false })

  assert.deepEqual(await readdir(quartoDir), ["computed.html"])
})

// Quarto listings glob the filesystem rather than the project render list.
// Measured: an unfiltered listing links an unpublished draft beside it and
// copies its raw source into the output tree. `include: { publish: true }`
// stops both, so the guard is on the listing rather than on the draft.
test("rejects a listing that does not filter on publish", async () => {
  const vault = await withVault({
    "articles/index.md": note("Articles", "publish: true\nlisting:\n  contents: \"*.qmd\"\n", "Section."),
  })

  const messages = await messagesFrom(() => vault.run())

  assert.equal(messages.length, 1)
  assert.match(messages[0], /listing does not filter on publish/)
})

test("allows a draft beside a listing that filters on publish", async () => {
  const vault = await withVault({
    "articles/index.md": note(
      "Articles",
      "publish: true\nlisting:\n  contents: \"*.qmd\"\n  include:\n    publish: true\n",
      "Section.",
    ),
    "articles/draft.qmd": note("Draft", "publish: false\n", "Not ready."),
  })

  const result = await vault.run()

  assert.equal(result.published.length, 1)
})

// `aliases:` means a name to Obsidian and a URL to Quarto, and Quarto resolves
// it against the aliasing document's directory. A display alias therefore
// publishes a junk redirect page, and a URL alias meant for the site root lands
// under the section instead.
test("rejects an alias that is not site-absolute", async () => {
  const vault = await withVault({
    "articles/index.md": note("Articles", "publish: true\naliases:\n  - Knowledge Notes\n", "Body"),
  })

  const messages = await messagesFrom(() => vault.run())

  assert.equal(messages.length, 1)
  assert.match(messages[0], /articles\/Knowledge Notes/)
})
